# Generated by Django 4.1.4 on 2022-12-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_civildata_link_csedata_link_eeedata_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csedata',
            name='last_date',
            field=models.DateTimeField(null=True),
        ),
    ]
